### PR TITLE
Test project cloning for conda

### PR DESCRIPTION
**Pull request by jimdowling**
https://hopshadoop.atlassian.net/browse/HOPSWORKS-536
and
https://hopshadoop.atlassian.net/browse/HOPSWORKS-544

### CODE REVIEW

**Comment by jimdowling** [comment]
Jenkins test this please.

**Comment by jimdowling** [comment]
Jenkins test this please.

**Comment by jimdowling** [comment]
Jenkins test this please.

**Comment by jimdowling** [comment]
Jenkins test this please.

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by jimdowling** [comment]
Jenkins test this please

**Comment by jimdowling** [comment]
Jenkins test this please.

**Comment by jimdowling** [comment]
Jenkins test this please.

**Comment by jimdowling** [comment]
Jenkins test this please.

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by jimdowling** [comment]
Jenkins test this please

**Comment by jimdowling** [comment]
Jenkins test this please

**Pull request closed without merging**
