### PR TITLE
[HOPSWORKS-426]

### PR DESCRIPTION
**Pull request by berthoug**
hopshadoop/hops-hadoop-chef#76
https://hopshadoop.atlassian.net/browse/HOPSWORKS-426

### CODE REVIEW

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by tkakantousis** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Pull request closed without merging**
