### PR TITLE
HOPSWORKS-94

### PR DESCRIPTION
**Pull request by o-alex**

### CODE REVIEW

**Comment by jimdowling** [comment]
jenkins test this please

**Comment by o-alex** [comment]
according to the documentation here:
http://hops.readthedocs.io/en/latest/developer_guide/guide/platform_testing.html
I thought making the PR here will trigger the jenkins tests. Is there doc on how to do that?

**Comment by SirOibaf** [comment]
jenkins test this please

**Comment by SirOibaf** [comment]
jenkins test this please

**Pull request closed without merging**
