### PR TITLE
[HOPSWORKS-587] Chef recipe bugfixes, upgrade to NDB 

### PR DESCRIPTION
**Pull request by jimdowling**
https://hopshadoop.atlassian.net/browse/HOPSWORKS-587

### CODE REVIEW

**Comment by tkakantousis** [comment]
jenkins test this please

**Comment by jimdowling** [comment]
jenkins test this please

**Comment by jimdowling** [comment]
jenkins test this please

**Comment by jimdowling** [comment]
jenkins test this please

**Comment by jimdowling** [comment]
jenkins test this please

**Comment by jimdowling** [comment]
jenkins test this please

**Pull request closed without merging**
