### PR TITLE
HOPSWORKS-382

### PR DESCRIPTION
**Pull request by jimdowling**

### CODE REVIEW

**Comment by jimdowling** [comment]
test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by jimdowling** [comment]
Jenkins, test this please

**Comment by jimdowling** [comment]
Jenkins test this please

**Comment by jimdowling** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins tests this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by jimdowling** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by jimdowling** [comment]
Jenkins test this please

**Comment by jimdowling** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Comment by SirOibaf** [comment]
Jenkins test this please

**Pull request closed without merging**
